# Generated by Django 4.2.7 on 2023-11-07 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('num_employees', models.IntegerField(null=True)),
                ('investment', models.IntegerField(null=True)),
                ('revenue', models.IntegerField(null=True)),
                ('homepage', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=200, null=True)),
                ('due_datetime', models.DateTimeField(default='2999-12-31')),
                ('min_wage', models.IntegerField(null=True)),
                ('max_wage', models.IntegerField(null=True)),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.company')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('geo_lat', models.FloatField()),
                ('geo_alt', models.FloatField()),
            ],
            options={
                'db_table': 'location_info',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tech_stack',
            },
        ),
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'welfare',
            },
        ),
        migrations.CreateModel(
            name='JobTechMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.job')),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.techstack')),
            ],
            options={
                'db_table': 'job_tech_mapping',
            },
        ),
        migrations.CreateModel(
            name='JobPositionMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.job')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.position')),
            ],
            options={
                'db_table': 'job_position_mapping',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='loc_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.locationinfo'),
        ),
        migrations.CreateModel(
            name='CompanyWelfareMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.company')),
                ('welfare_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.welfare')),
            ],
            options={
                'db_table': 'company_welfare_mapping',
            },
        ),
        migrations.CreateModel(
            name='CompanyTechMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.company')),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.techstack')),
            ],
            options={
                'db_table': 'company_tech_mapping',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='loc_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.locationinfo'),
        ),
    ]
