# Generated by Django 4.2.7 on 2023-11-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_company_loc_info_id_alter_job_loc_info_id'),
        ('data', '0002_company_welfare_alter_company_loc_info_id_and_more'),
    ]

    operations = [
    ]
